# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-25 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0005_auto_20190624_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicuser',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_user', to='ps_com.Clinic'),
        ),
        migrations.AlterField(
            model_name='clinicuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_clinic', to=settings.AUTH_USER_MODEL),
        ),
    ]
