# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-26 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0006_auto_20190625_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='picture',
        ),
    ]
