# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-29 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0007_remove_patient_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetails',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_details', to='ps_com.Patient'),
        ),
    ]
