# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0008_auto_20190629_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_bill', to='ps_com.AppointmentDetails'),
        ),
    ]
