# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-04 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0009_auto_20190702_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='status',
            field=models.CharField(blank=True, choices=[(b'Open', b'Open'), (b'Canceled', b'Canceled')], default=b'Open', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cnic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
