# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0010_auto_20190704_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='appointment_time',
            field=models.CharField(blank=True, help_text=b'eg: AM 10:00', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='appointment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
