# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-30 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ps_com', '0011_auto_20190708_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientXRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'patient/xray/')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_xray', to='ps_com.Patient')),
            ],
        ),
    ]
